// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"apiapi/app"
	"apiapi/controller"
	"apiapi/repository"
	"apiapi/service"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func initProductAPI(db *gorm.DB) *app.BllAPI {
	product := &repository.Product{
		DB: db,
	}
	serviceProduct := &service.Product{
		ProductRepository: product,
	}
	controllerProduct := &controller.Product{
		ProductService: serviceProduct,
	}
	blog := &repository.Blog{
		DB: db,
	}
	serviceBlog := &service.Blog{
		BlogRepository: blog,
	}
	controllerBlog := &controller.Blog{
		BlogService: serviceBlog,
	}
	bllAPI := &app.BllAPI{
		ProductAPI: controllerProduct,
		BlogAPI:    controllerBlog,
	}
	return bllAPI
}
