// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package router

import (
	"apiapi/API"
	"apiapi/repository"
	"apiapi/service"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func initProductAPI(db *gorm.DB) *API.ProductAPI {
	productRepository := repository.NewProductRepostiory(db)
	productService := service.NewProductService(productRepository)
	productAPI := API.NewProductAPI(productService)
	return productAPI
}
